spring:
  application:
    name: qing-gateway
  redis:
    host: 47.113.189.237
    port: 6379
    password: cong0917
    timeout: 5000
    connect-timeout: 5000

server:
  port: 8101

qing:
  admin:
    infos:
      - url: localhost:9099
  server:
    load-balance: round_robin
    timeout-millis: 5000
    cache-refresh-interval-millis: 10000
    websocket-port: 9999
  routes:
    - uri: traffic
      predicates: /test
      priority: 100
  web:
    client:
      pending-acquire-timeout: 25 # 超时时间 单位秒
      pending-acquire-max-count: 10000 # 最大等待数
      max-connections: 1000 # 最大连接数
      max-idle-time: 30 # 最大空闲时间 单位秒
      work-counts: 10 # 线程数